### ISSUE TITLE
getConversationList获取会话列表，内容和未读信息为空

### ISSUE THREAD

**Issue by ljcGitHub** [maxim-top/lanying-im-web#2]
在web示例中，im.userManage.getConversationList()返回数据不符合预期的结果

![image](https://user-images.githubusercontent.com/23240424/103274372-78ab2380-49fc-11eb-8c3f-f05d2751ba5a.png)

![image](https://user-images.githubusercontent.com/23240424/103274389-82cd2200-49fc-11eb-896f-7f20e05c33ab.png)

**Comment by ericliang** [comment]
你好，感谢提问，根据截图内容来看，数组已经有了内容。不符合预期的意思是？

**Comment by ljcGitHub** [comment]
好像是跨端的原因，现在还在测试是不是这个原因，已读系统会自动发起的吗，还是必须是客户端自己调起来------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Eric&amp;nbsp;Liang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月30日(星期三) 中午11:45
收件人:&nbsp;&quot;maxim-top/maxim-web&quot;<maxim-web@noreply.github.com&gt;;
抄送:&nbsp;&quot;北极丶星&quot;<523252797@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [maxim-top/maxim-web] getConversationList获取会话列表，内容和未读信息为空 (#2)

**Comment by ericliang** [comment]
我没理解错的话，你是想问如果未读数更新后是否会自动刷新吗？底层数据是会自动更新的，然后界面刷新依靠 watch 机制 https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/contact/conConversation.vue#L48

**Comment by ljcGitHub** [comment]
好，那意思是IM在界面上会自动判断是否已读的吧，UI需要自己判断然后刷新，对吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maxim-top/maxim-web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 中午12:43
收件人:&nbsp;"maxim-top/maxim-web"<maxim-web@noreply.github.com&gt;;
抄送:&nbsp;"超"<523252797@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [maxim-top/maxim-web] getConversationList获取会话列表，内容和未读信息为空 (#2)





 
我没理解错的话，你是想问如果未读数更新后是否会自动刷新吗？底层数据是会自动更新的，然后界面刷新依靠 watch 机制 https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/contact/conConversation.vue#L48
