### ISSUE TITLE
如何上传录制的音频

### ISSUE THREAD

**Issue by spencer17x** [maxim-top/lanying-im-web#4]
通过录制下来的音频是 blob/base64/buffer，如何发送该数据？貌似没有demo样例参考，文档也没说明。

**Comment by theorix** [comment]
可以参考下面链接： https://github.com/maxim-top/maxim-web/blob/d80514407233e3a6917b462417c5a8aafbbdf7fd/src/ui/chatting/content/roster/inputer.vue#L96  

im.sysManage.asyncFileUpload的参数fileType现在只支持mp3和amr：  如果文件为mp3格式，需要设置fileType为 'audio-mp3' ；如果为amr格式，需要设置fileType为 'audio'

**Comment by spencer17x** [comment]
如果要上传的话，这样录制的文件名怎么定义？这样会存在语音覆盖的问题

**Comment by spencer17x** [comment]
而且我试了下，fileType 为 'audio-mp3' 是无效的

**Comment by theorix** [comment]
文件名应该是你生成的，可以用时间戳和随机数保证不重复。asyncFileUpload的file参数需要传的是File对象 （ 见https://developer.mozilla.org/zh-CN/docs/Web/API/File/File ），audio-mp3 应该是有效的，无效是指报错了吗，有具体的错误信息吗。

**Comment by spencer17x** [comment]
@theorix 是file对象，上传 audio-mp3 会变成 text 的，设置 audio 就可以了。

**Comment by theorix** [comment]
变成text是因为this.im.sysManage.sendRosterMessage({type: this.fileType,  这里的type不支持audio-mp3 , 可以把asyncFileUpload的fileType 设置为'audio-mp3', 然后sendRosterMessage的type设置为'audio'。 
另外之前的把asyncFileUpload的fileType 设置为'audio'，但是文件不是amr，这种会导致手机端无法播放。

**Comment by spencer17x** [comment]
这些问题是不是应该补充到文档里或者demo里会比较好，还有用户发送语音的时候还得走一遍上传，这是不是直接暴露一个 api 更好一些呢？貌似安卓端是一个api吧？

**Comment by theorix** [comment]
好的 谢谢你的建议 我向相关人员反馈下
