### ISSUE TITLE
账号在另外的设备上登录了，原来的设备有监听吗

### ISSUE THREAD

**Issue by cdyxc** [maxim-top/lanying-im-web#6]

**Comment by theorix** [comment]
可以的，有个flooNotice 事件，参考 https://github.com/maxim-top/maxim-web/blob/b0bf5645000a24cc62b6873e9a7f27d0a05c5f3f/src/ui/index.vue#L168  
desc的取值：
"DEVICE_LOGIN"              其它设备登录 
"DEVICE_LOGOUT"             其它设备登出 
"DEVICE_ADDED"              增加新设备
"DEVICE_REMOVED"            移除设备
